# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joagz/Desktop/c++-astar/source

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joagz/Desktop/c++-astar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joagz/Desktop/c++-astar/CMakeFiles /home/joagz/Desktop/c++-astar//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joagz/Desktop/c++-astar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Astar

# Build rule for target.
Astar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Astar
.PHONY : Astar

# fast build rule for target.
Astar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astar.dir/build.make CMakeFiles/Astar.dir/build
.PHONY : Astar/fast

#=============================================================================
# Target rules for targets named map

# Build rule for target.
map: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 map
.PHONY : map

# fast build rule for target.
map/fast:
	$(MAKE) $(MAKESILENT) -f map/CMakeFiles/map.dir/build.make map/CMakeFiles/map.dir/build
.PHONY : map/fast

#=============================================================================
# Target rules for targets named astarpathfinder

# Build rule for target.
astarpathfinder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 astarpathfinder
.PHONY : astarpathfinder

# fast build rule for target.
astarpathfinder/fast:
	$(MAKE) $(MAKESILENT) -f astar/CMakeFiles/astarpathfinder.dir/build.make astar/CMakeFiles/astarpathfinder.dir/build
.PHONY : astarpathfinder/fast

astar.o: astar.cc.o
.PHONY : astar.o

# target to build an object file
astar.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astar.dir/build.make CMakeFiles/Astar.dir/astar.cc.o
.PHONY : astar.cc.o

astar.i: astar.cc.i
.PHONY : astar.i

# target to preprocess a source file
astar.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astar.dir/build.make CMakeFiles/Astar.dir/astar.cc.i
.PHONY : astar.cc.i

astar.s: astar.cc.s
.PHONY : astar.s

# target to generate assembly for a file
astar.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astar.dir/build.make CMakeFiles/Astar.dir/astar.cc.s
.PHONY : astar.cc.s

astar/astarnode.o: astar/astarnode.cc.o
.PHONY : astar/astarnode.o

# target to build an object file
astar/astarnode.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astar.dir/build.make CMakeFiles/Astar.dir/astar/astarnode.cc.o
.PHONY : astar/astarnode.cc.o

astar/astarnode.i: astar/astarnode.cc.i
.PHONY : astar/astarnode.i

# target to preprocess a source file
astar/astarnode.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astar.dir/build.make CMakeFiles/Astar.dir/astar/astarnode.cc.i
.PHONY : astar/astarnode.cc.i

astar/astarnode.s: astar/astarnode.cc.s
.PHONY : astar/astarnode.s

# target to generate assembly for a file
astar/astarnode.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astar.dir/build.make CMakeFiles/Astar.dir/astar/astarnode.cc.s
.PHONY : astar/astarnode.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Astar"
	@echo "... astarpathfinder"
	@echo "... map"
	@echo "... astar.o"
	@echo "... astar.i"
	@echo "... astar.s"
	@echo "... astar/astarnode.o"
	@echo "... astar/astarnode.i"
	@echo "... astar/astarnode.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

